### ISSUE TITLE
Error: Cannot find module './aurelia-bootstrap-datetimepicker'.

### ISSUE THREAD

**Issue by miromarchi** [ghiscoding/Aurelia-Bootstrap-Plugins#37] opened 2018-01-09 16:45 UTC
My setup **aurelia, typescript,  webpack** (using an old version of the skeleton, which i update manually)
aurelia-webpack-plugin": "^2.0.0-rc.5",
"webpack": "2.7.0",
"webpack-dev-server": "2.9.4",

Steps I have done:
* Install package via `yarn add aurelia-bootstrap-datetimepicker -D`
* Edit `main.ts` with import
```
import 'aurelia-bootstrap-datetimepicker';
import 'eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css';
```
and plugin 
`.plugin('aurelia-bootstrap-datetimepicker');`
(also tried the syntax `.plugin(PLATFORM.moduleName('aurelia-bootstrap-datetimepicker'));` since I have `aurelia-webpack-plugin 2`

This setup throws the error in issue title `Error: Cannot find module './aurelia-bootstrap-datetimepicker'.`
I tried to import the module in different ways, with no success.

I have other plugins installed and working with the same procedure. E.g. aurelia-configuration and aurelia-google-analytics.
I think i might be missing something simple :D any suggestions?
thanks

**Comment by ghiscoding** [comment] 2018-01-09 17:35
You probably have a syntax error somewhere, please review the [README](https://github.com/ghiscoding/Aurelia-Bootstrap-Plugins/tree/master/aurelia-bootstrap-datetimepicker) for installation and/or look at the client samples and maybe the [doc](https://github.com/ghiscoding/Aurelia-Bootstrap-Plugins/tree/master/doc) for a TypeScript WebPack2 project. The plugin is working fine, I used it last weekend. 

And you do need the `PLATFORM.moduleName` syntax with WebPack2, it won't work without it and will throw some errors similar to what you described.

**Comment by ghiscoding** [comment] 2018-01-13 19:18
Are you running WebPack through the `Aurelia-CLI` by any change? I am using WebPack directly without the CLI (with `npm start`) and for that work, you also have to update your [webpack.config.js](https://github.com/ghiscoding/Aurelia-Bootstrap-Plugins/tree/master/aurelia-bootstrap-datetimepicker#aurelia-webpack) file. I never got the Aurelia-CLI working correctly with WebPack since I use a custom installation, it throws an error when I try to run `au run` but it works with `npm start`, so I never bothered opening a CLI issue. Anyhow, can you please modify your webpack config and try running it through `npm start`

**Comment by ghiscoding** [comment] 2018-01-23 00:10
I might end up closing this issue if I get no feedback and/or a way to reproduce the error. As a reminder, the lib itself includes multiple `client` samples, you can clone it and try to install any of the `client` folder (or even the `doc` folder)

**Comment by ghiscoding** [comment] 2018-01-31 04:59
closing for no feedback or ways to reproduce

**Closed as completed by ghiscoding** 2018-01-31 04:59 UTC

**Comment by miromarchi** [comment] 2018-02-16 11:18
Sorry for the delay in feedback. thanks for checking this out.
I still can't use it.
I tried to use various combinations of the module path and module name, but no luck. Sorry i don't have the time to check this out more.
