### ISSUE TITLE
Aurelia-Bootstrap-Select is slow with large dataset

### ISSUE THREAD

**Issue by johntom** [ghiscoding/Aurelia-Bootstrap-Plugins#63] opened 2018-09-04 11:46 UTC
I've cutover from https://tochoromero.github.io/aurelia-bootstrap typeahead to bootstrap-select. I have an issue when the select list is comprised of a large dataset (>14000 records). In this case the dialog takes over 6 seconds to open where the typeahead soultion instantly opens. Can you recommend a way to improve the performance using  bootstrap-select?

**Comment by ghiscoding** [comment] 2018-09-04 13:09
Hmm I don't think Bootstrap-Select would handle that many records, it was never made to support huge list. With huge list, you should think of using something else, like typeahead. I'm actually surprised that it doesn't take more than 6sec., you probably haven't tried IE yet, that's probably more.

**Comment by ghiscoding** [comment] 2018-09-07 22:18
This is slowdown is most probably coming from the core library itself and is probably caused by the time it takes to render the HTML for 14000 `ul > li` DOM elements, I don't think there's is anything that can be done in my lib to fix this. I strongly suggest to use a Typeahead element for that particular use case. With that information, I'll have to close this issue. I can reopen the issue if any there's any relevant info coming up

**Closed as completed by ghiscoding** 2018-09-07 22:18 UTC
Labels: wontfix

**Comment by johntom** [comment] 2018-09-08 17:11
Thanks for reply and yes went back to the typeahead from  https://tochoromero.github.io/aurelia-bootstrap. Was concerned due to lack of response and activity at that repo.

**Comment by ghiscoding** [comment] 2018-09-08 17:56
Yeah I also saw there wasn't any updates in a year on that lib. I also thought of doing a typeahead and make it work with Bootstrap 3/4, but that takes time which is hard to find. 

Bootstrap-Select serve a different purpose and are good to use with a max of couple of hundreds.

**Comment by johntom** [comment] 2018-09-08 19:49
Well you have a good model as it works very well shd you ever do it.
